version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build  # Builds the project
  post_build:
    commands:
      - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app)
